<a href="https://colab.research.google.com/github/mismatchgit/PyTorch-tutorial-freecodecamp/blob/main/PyTorch_for_Deep_Learning_%26_Machine_Learning_Full_Course_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)
print(np.__version__)
print(pd.__version__)

2.6.0+cu124
2.0.2
2.2.2


## Intro to Tensor
### Creating Tensors

In [2]:
#scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
#Get Tensor as int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX =torch.tensor ([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# TEnsor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR2 = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]],
                        [[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]]],
                        [[[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]],
                        [[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR2.ndim

4

In [13]:
TENSOR2.shape

torch.Size([2, 2, 4, 3])

In [14]:
TENSOR2[0][1]

tensor([[2, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [1, 5, 7]])

## Random Tensors

In [15]:
#create a random tensor
random_tensor = torch.rand(3,3,5)
random_tensor

tensor([[[0.2087, 0.8583, 0.7211, 0.7225, 0.7868],
         [0.4491, 0.8487, 0.4163, 0.0237, 0.1126],
         [0.4151, 0.9510, 0.0363, 0.3547, 0.3769]],

        [[0.2826, 0.2567, 0.9086, 0.1411, 0.8738],
         [0.9585, 0.5039, 0.2618, 0.2902, 0.9835],
         [0.2415, 0.5648, 0.3023, 0.1863, 0.0074]],

        [[0.5607, 0.7263, 0.2650, 0.8154, 0.3279],
         [0.4200, 0.7573, 0.7905, 0.3894, 0.6233],
         [0.2274, 0.5487, 0.5428, 0.0461, 0.8326]]])

In [16]:
#create a random tensor with similar shape to an image sensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #Height, width, RGB(Color channel)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeroes and Ones

In [17]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros*random_tensor

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 2

In [19]:
#Create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [21]:
torch.range(0,10)

<ipython-input-21-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=random_tensor)
ten_zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

## Tensor Datatypes
Note: Top 3 Errors


1.   tensors not right datatype
1.   tensors not righht shape (In the case of zeros*random_tensor)
2.   tensors not in the right device






In [25]:
#Float Tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #cpu.gpu,tpu,cuda etc
                               requires_grad=False) #whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [26]:
float_32_tensor.dtype

torch.float32

In [27]:
#converting data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Tensor Manipulation

In [39]:
#tensor Multiplication
mul_tensor = torch.tensor([1,2,3])
print(mul_tensor * 10)
matrix_mul_tensor1 = torch.tensor([[1,2,3],
                                 [4,5,6]])
matrix_mul_tensor1.shape
matrix_mul_tensor2 = torch.tensor([[3,2,1],
                                 [6,5,4]])
matrix_mul_tensor2.shape
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2)#doesn't work as expected (Shape mismatch)
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2.T)#Transposes the tensor

tensor([10, 20, 30])


tensor([[10, 28],
        [28, 73]])

In [44]:
#difference between amtmul and for_loop
%%time
value = torch.zeros(size=(2,2))
matrix_mul_tensor2T = matrix_mul_tensor2.T
for i in range(matrix_mul_tensor1.shape[0]):
  for j in range(matrix_mul_tensor2T.shape[1]):
    for k in range(matrix_mul_tensor2T.shape[0]):
      value[i,j] += matrix_mul_tensor1[i][k] * matrix_mul_tensor2T[k][j]

print(value)

tensor([[10., 28.],
        [28., 73.]])
CPU times: user 2.69 ms, sys: 0 ns, total: 2.69 ms
Wall time: 2.56 ms


In [56]:
%%time
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2.T)#Transposes the tensor

CPU times: user 633 µs, sys: 0 ns, total: 633 µs
Wall time: 506 µs


tensor([[10, 28],
        [28, 73]])

In [57]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = torch.tensor([[1, 2, 3],
                  [3, 4, 5],
                  [5, 6, 7]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 3])

Output:
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [2.2952, 1.8148, 2.7918, 1.2092, 2.7499, 2.3454],
        [3.8659, 2.8555, 3.9257, 1.5819, 4.3161, 3.2432]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Tensor Aggregation

In [49]:
#need to convert datatype for getting mean()
x = torch.arange(1,100,5)
x.type(torch.float32).mean()

tensor(48.5000)

## Finding positional min and max

In [50]:
x.argmin()

tensor(0)

In [51]:
x.argmax()

tensor(19)

## Reshaping, stacking, squeezing and unsqueezing tensors