<a href="https://colab.research.google.com/github/mismatchgit/PyTorch-tutorial-freecodecamp/blob/main/Pytorch_Fundamentals_Exercise_Solution_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1 Documentation Reading

## 2 Create a random tensor with shape (7, 7).

In [4]:
import torch
random_tensor = torch.rand(7, 7)
print(random_tensor)

tensor([[0.5244, 0.5943, 0.1923, 0.8416, 0.2305, 0.2629, 0.3286],
        [0.7882, 0.3281, 0.7909, 0.1008, 0.5670, 0.9414, 0.2254],
        [0.8519, 0.8614, 0.3059, 0.3006, 0.0856, 0.1784, 0.1326],
        [0.7273, 0.7378, 0.0351, 0.3835, 0.3354, 0.5081, 0.7816],
        [0.2051, 0.7283, 0.5884, 0.2830, 0.5718, 0.3757, 0.9625],
        [0.2396, 0.3895, 0.9330, 0.1968, 0.0082, 0.9241, 0.3237],
        [0.1650, 0.1887, 0.9857, 0.6292, 0.5334, 0.8143, 0.4432]])


# 3 Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7)

In [5]:
another_random_tensor = torch.rand(1,7)
result = torch.matmul(random_tensor, another_random_tensor.T)
print(result)

tensor([[1.5076],
        [2.1881],
        [0.9929],
        [1.5610],
        [2.1069],
        [2.1252],
        [2.7323]])


## 4 Set the random seed to 0 and do exercises 2 & 3 over again.

In [6]:
random_seed = 0
torch.manual_seed(random_seed)
random_tensor2 = torch.rand(7,7)

torch.manual_seed(random_seed)
another_random_tensor2 = torch.rand(1,7)
result2 = torch.matmul(random_tensor2, another_random_tensor2.T)
print(result2)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


## 5 GPU equivalent for manual seed

In [9]:
torch.cuda.manual_seed(1234)

## 6 Create two random tensors of shape (2, 3) and send them both to the GPU

In [22]:
import torch

torch.manual_seed(1234)
random_tensor3= torch.rand(2,3)
random_tensor4= torch.rand(2,3)
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.manual_seed(1234)
gpu_random_tensor3 = random_tensor3.to(device)
gpu_random_tensor4 = random_tensor4.to(device)
gpu_random_tensor3,gpu_random_tensor3.device

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 device(type='cuda', index=0))

In [28]:
# in the previous code cuda.manual_seed did not work. to make it work have to set it when generating
device = "cuda" if torch.cuda.is_available() else "cpu"
torch.cuda.manual_seed(1234)
gpu_random_tensor6= torch.rand(2,3,device=device)

gpu_random_tensor6


tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

## 7 Perform a matrix multiplication on the tensors you created in 6

In [12]:
result = torch.matmul(gpu_random_tensor3, gpu_random_tensor4.T)
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

## 8 Find the maximum and minimum values of the output of 7.

In [15]:
result.max(), result.min()

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

## 9 Find the maximum and minimum index values of the output of 7.

In [16]:
result.argmax(), result.argmin()

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

## 10 Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [20]:
torch.manual_seed(7)
random_tensor5 = torch.rand(1,1,1,10)
random_tensor5, random_tensor5.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [21]:
squeezed_random_tensor5 = random_tensor5.squeeze()
squeezed_random_tensor5, squeezed_random_tensor5.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))