<a href="https://colab.research.google.com/github/mismatchgit/PyTorch-tutorial-freecodecamp/blob/main/PyTorch_for_Deep_Learning_%26_Machine_Learning_Full_Course_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)
print(np.__version__)
print(pd.__version__)

2.6.0+cu124
2.0.2
2.2.2


## Intro to Tensor
### Creating Tensors

In [ ]:
#scalars
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get Tensor as int
scalar.item()

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX =torch.tensor ([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TEnsor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4,5]]])

TENSOR2 = torch.tensor([[[[1,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]],
                        [[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]]],
                        [[[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]],
                        [[2,2,3],
                        [3,6,9],
                        [2,4,5],
                        [1,5,7]]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR2.ndim

4

In [ ]:
TENSOR2.shape

torch.Size([2, 2, 4, 3])

In [ ]:
TENSOR2[0][1]

tensor([[2, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [1, 5, 7]])

## Random Tensors

In [ ]:
#create a random tensor
random_tensor = torch.rand(3,3,5)
random_tensor

tensor([[[0.2087, 0.8583, 0.7211, 0.7225, 0.7868],
         [0.4491, 0.8487, 0.4163, 0.0237, 0.1126],
         [0.4151, 0.9510, 0.0363, 0.3547, 0.3769]],

        [[0.2826, 0.2567, 0.9086, 0.1411, 0.8738],
         [0.9585, 0.5039, 0.2618, 0.2902, 0.9835],
         [0.2415, 0.5648, 0.3023, 0.1863, 0.0074]],

        [[0.5607, 0.7263, 0.2650, 0.8154, 0.3279],
         [0.4200, 0.7573, 0.7905, 0.3894, 0.6233],
         [0.2274, 0.5487, 0.5428, 0.0461, 0.8326]]])

In [ ]:
#create a random tensor with similar shape to an image sensor
random_image_size_tensor = torch.rand(size=(3,224,224)) #Height, width, RGB(Color channel)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeroes and Ones

In [ ]:
# Create a tensor of all zeroes
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

RuntimeError: The size of tensor a (4) must match the size of tensor b (5) at non-singleton dimension 2

In [ ]:
#Create a tensor of ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

##Creating a range of tensors and tensors-like

In [ ]:
torch.range(0,10)

<ipython-input-21-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
one_to_ten = torch.arange(0,10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#creating tensors-like
ten_zeros = torch.zeros_like(input=random_tensor)
ten_zeros

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

## Tensor Datatypes
Note: Top 3 Errors


1.   tensors not right datatype
1.   tensors not righht shape (In the case of zeros*random_tensor)
2.   tensors not in the right device






In [ ]:
#Float Tensors
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                               device=None, #cpu.gpu,tpu,cuda etc
                               requires_grad=False) #whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
#converting data type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

## Tensor Manipulation

In [ ]:
#tensor Multiplication
mul_tensor = torch.tensor([1,2,3])
print(mul_tensor * 10)
matrix_mul_tensor1 = torch.tensor([[1,2,3],
                                 [4,5,6]])
matrix_mul_tensor1.shape
matrix_mul_tensor2 = torch.tensor([[3,2,1],
                                 [6,5,4]])
matrix_mul_tensor2.shape
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2)#doesn't work as expected (Shape mismatch)
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2.T)#Transposes the tensor

tensor([10, 20, 30])


tensor([[10, 28],
        [28, 73]])

In [ ]:
#difference between amtmul and for_loop
%%time
value = torch.zeros(size=(2,2))
matrix_mul_tensor2T = matrix_mul_tensor2.T
for i in range(matrix_mul_tensor1.shape[0]):
  for j in range(matrix_mul_tensor2T.shape[1]):
    for k in range(matrix_mul_tensor2T.shape[0]):
      value[i,j] += matrix_mul_tensor1[i][k] * matrix_mul_tensor2T[k][j]

print(value)

tensor([[10., 28.],
        [28., 73.]])
CPU times: user 2.69 ms, sys: 0 ns, total: 2.69 ms
Wall time: 2.56 ms


In [ ]:
%%time
torch.matmul(matrix_mul_tensor1,matrix_mul_tensor2.T)#Transposes the tensor

CPU times: user 633 µs, sys: 0 ns, total: 633 µs
Wall time: 506 µs


tensor([[10, 28],
        [28, 73]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=3, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = torch.tensor([[1, 2, 3],
                  [3, 4, 5],
                  [5, 6, 7]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 3])

Output:
tensor([[0.7245, 0.7740, 1.6579, 0.8366, 1.1836, 1.4476],
        [2.2952, 1.8148, 2.7918, 1.2092, 2.7499, 2.3454],
        [3.8659, 2.8555, 3.9257, 1.5819, 4.3161, 3.2432]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


## Tensor Aggregation

In [ ]:
#need to convert datatype for getting mean()
x = torch.arange(1,100,5)
x.type(torch.float32).mean()

tensor(48.5000)

## Finding positional min and max

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(19)

## Reshaping, stacking, squeezing and unsqueezing tensors

In [5]:
import torch
x = torch.arange(1.,101.)
x, x.shape

(tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
          25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
          37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
          49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
          61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
          73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
          85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
          97.,  98.,  99., 100.]),
 torch.Size([100]))

In [10]:
#add dimension
#x_reshaped = x.reshape(10,10)
#x_reshaped = x.reshape(2,5,10)
x_reshaped = x.reshape(2,2,5,5)
x_reshaped, x_reshaped.shape,x_reshaped.ndim

(tensor([[[[  1.,   2.,   3.,   4.,   5.],
           [  6.,   7.,   8.,   9.,  10.],
           [ 11.,  12.,  13.,  14.,  15.],
           [ 16.,  17.,  18.,  19.,  20.],
           [ 21.,  22.,  23.,  24.,  25.]],
 
          [[ 26.,  27.,  28.,  29.,  30.],
           [ 31.,  32.,  33.,  34.,  35.],
           [ 36.,  37.,  38.,  39.,  40.],
           [ 41.,  42.,  43.,  44.,  45.],
           [ 46.,  47.,  48.,  49.,  50.]]],
 
 
         [[[ 51.,  52.,  53.,  54.,  55.],
           [ 56.,  57.,  58.,  59.,  60.],
           [ 61.,  62.,  63.,  64.,  65.],
           [ 66.,  67.,  68.,  69.,  70.],
           [ 71.,  72.,  73.,  74.,  75.]],
 
          [[ 76.,  77.,  78.,  79.,  80.],
           [ 81.,  82.,  83.,  84.,  85.],
           [ 86.,  87.,  88.,  89.,  90.],
           [ 91.,  92.,  93.,  94.,  95.],
           [ 96.,  97.,  98.,  99., 100.]]]]),
 torch.Size([2, 2, 5, 5]),
 4)

In [12]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 100)
z, z.shape

(tensor([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
           13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
           25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
           37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
           49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
           61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
           73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
           85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
           97.,  98.,  99., 100.]]),
 torch.Size([1, 100]))

In [13]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[  5.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
           13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
           25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
           37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
           49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
           61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
           73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
           85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
           97.,  98.,  99., 100.]]),
 tensor([  5.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
          13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
          25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
          37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  

In [20]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[  5.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
           13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
           25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
           37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
           49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
           61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
           73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
           85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
           97.,  98.,  99., 100.],
         [  5.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
           13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
           25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
           37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,

In [32]:
# Remove extra dimension from x_reshaped
x_squeezed = x_stacked.squeeze()#No change as there is no dimension of size 1
x_squeezed = x_stacked.squeeze(dim=1)#No change as there is no dimension of size 1
x_squeezed = x_reshaped.squeeze(dim=1)#No change as there is no dimension of size 1
x_reshaped2 = x.reshape(1,1,1,2,2,5,5)
x_squeezed2 = x_reshaped2.squeeze(dim=1)#Deletes 1 dimension of size 1 (Previously it was 3) dimension of size 1
x_squeezed2, x_squeezed2.shape

(tensor([[[[[[  5.,   2.,   3.,   4.,   5.],
             [  6.,   7.,   8.,   9.,  10.],
             [ 11.,  12.,  13.,  14.,  15.],
             [ 16.,  17.,  18.,  19.,  20.],
             [ 21.,  22.,  23.,  24.,  25.]],
 
            [[ 26.,  27.,  28.,  29.,  30.],
             [ 31.,  32.,  33.,  34.,  35.],
             [ 36.,  37.,  38.,  39.,  40.],
             [ 41.,  42.,  43.,  44.,  45.],
             [ 46.,  47.,  48.,  49.,  50.]]],
 
 
           [[[ 51.,  52.,  53.,  54.,  55.],
             [ 56.,  57.,  58.,  59.,  60.],
             [ 61.,  62.,  63.,  64.,  65.],
             [ 66.,  67.,  68.,  69.,  70.],
             [ 71.,  72.,  73.,  74.,  75.]],
 
            [[ 76.,  77.,  78.,  79.,  80.],
             [ 81.,  82.,  83.,  84.,  85.],
             [ 86.,  87.,  88.,  89.,  90.],
             [ 91.,  92.,  93.,  94.,  95.],
             [ 96.,  97.,  98.,  99., 100.]]]]]]),
 torch.Size([1, 1, 2, 2, 5, 5]))

In [27]:
# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed, x_unsqueezed.shape

(tensor([[[[[  5.,   2.,   3.,   4.,   5.],
            [  6.,   7.,   8.,   9.,  10.],
            [ 11.,  12.,  13.,  14.,  15.],
            [ 16.,  17.,  18.,  19.,  20.],
            [ 21.,  22.,  23.,  24.,  25.]],
 
           [[ 26.,  27.,  28.,  29.,  30.],
            [ 31.,  32.,  33.,  34.,  35.],
            [ 36.,  37.,  38.,  39.,  40.],
            [ 41.,  42.,  43.,  44.,  45.],
            [ 46.,  47.,  48.,  49.,  50.]]],
 
 
          [[[ 51.,  52.,  53.,  54.,  55.],
            [ 56.,  57.,  58.,  59.,  60.],
            [ 61.,  62.,  63.,  64.,  65.],
            [ 66.,  67.,  68.,  69.,  70.],
            [ 71.,  72.,  73.,  74.,  75.]],
 
           [[ 76.,  77.,  78.,  79.,  80.],
            [ 81.,  82.,  83.,  84.,  85.],
            [ 86.,  87.,  88.,  89.,  90.],
            [ 91.,  92.,  93.,  94.,  95.],
            [ 96.,  97.,  98.,  99., 100.]]]]]),
 torch.Size([1, 2, 2, 5, 5]))

In [31]:
# To change the position of the dimensions Permute is used
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted, x_permuted.shape

(tensor([[[0.1783, 0.6030, 0.8992,  ..., 0.5292, 0.8818, 0.3187],
          [0.0035, 0.7748, 0.9046,  ..., 0.0570, 0.7450, 0.7444],
          [0.4878, 0.2100, 0.6676,  ..., 0.9207, 0.7554, 0.4190],
          ...,
          [0.3658, 0.1195, 0.9950,  ..., 0.1966, 0.5990, 0.1575],
          [0.1272, 0.0915, 0.6221,  ..., 0.7180, 0.1558, 0.0045],
          [0.4201, 0.6458, 0.1050,  ..., 0.8083, 0.4406, 0.1997]],
 
         [[0.4693, 0.3284, 0.2153,  ..., 0.0852, 0.6656, 0.6704],
          [0.1792, 0.5663, 0.3717,  ..., 0.2591, 0.6906, 0.2798],
          [0.0832, 0.2282, 0.0964,  ..., 0.1763, 0.0286, 0.9204],
          ...,
          [0.4662, 0.6223, 0.9335,  ..., 0.8285, 0.1261, 0.3387],
          [0.2716, 0.4090, 0.5059,  ..., 0.9728, 0.2009, 0.0771],
          [0.7208, 0.6750, 0.6350,  ..., 0.0296, 0.4072, 0.7067]],
 
         [[0.9267, 0.7568, 0.1347,  ..., 0.4097, 0.3948, 0.9424],
          [0.9481, 0.3546, 0.4594,  ..., 0.3637, 0.3275, 0.4807],
          [0.5893, 0.9707, 0.7860,  ...,

In [34]:
x_original[0,0,0]=111
x_original[0,0,0],x_permuted

(tensor(111.),
 tensor([[[1.1100e+02, 6.0300e-01, 8.9924e-01,  ..., 5.2917e-01,
           8.8178e-01, 3.1872e-01],
          [3.5288e-03, 7.7476e-01, 9.0457e-01,  ..., 5.7013e-02,
           7.4498e-01, 7.4443e-01],
          [4.8775e-01, 2.0997e-01, 6.6761e-01,  ..., 9.2070e-01,
           7.5541e-01, 4.1903e-01],
          ...,
          [3.6580e-01, 1.1946e-01, 9.9499e-01,  ..., 1.9656e-01,
           5.9899e-01, 1.5754e-01],
          [1.2723e-01, 9.1494e-02, 6.2215e-01,  ..., 7.1800e-01,
           1.5579e-01, 4.5336e-03],
          [4.2008e-01, 6.4584e-01, 1.0500e-01,  ..., 8.0825e-01,
           4.4060e-01, 1.9966e-01]],
 
         [[4.6932e-01, 3.2843e-01, 2.1532e-01,  ..., 8.5172e-02,
           6.6565e-01, 6.7043e-01],
          [1.7916e-01, 5.6625e-01, 3.7166e-01,  ..., 2.5906e-01,
           6.9057e-01, 2.7978e-01],
          [8.3189e-02, 2.2817e-01, 9.6415e-02,  ..., 1.7629e-01,
           2.8562e-02, 9.2035e-01],
          ...,
          [4.6615e-01, 6.2228e-01, 9.3346e-

## Indexing in Tensors

In [35]:
# create a tensor
x = torch.arange(1,101).reshape(1,2,2,5,5)
x, x.shape

(tensor([[[[[  1,   2,   3,   4,   5],
            [  6,   7,   8,   9,  10],
            [ 11,  12,  13,  14,  15],
            [ 16,  17,  18,  19,  20],
            [ 21,  22,  23,  24,  25]],
 
           [[ 26,  27,  28,  29,  30],
            [ 31,  32,  33,  34,  35],
            [ 36,  37,  38,  39,  40],
            [ 41,  42,  43,  44,  45],
            [ 46,  47,  48,  49,  50]]],
 
 
          [[[ 51,  52,  53,  54,  55],
            [ 56,  57,  58,  59,  60],
            [ 61,  62,  63,  64,  65],
            [ 66,  67,  68,  69,  70],
            [ 71,  72,  73,  74,  75]],
 
           [[ 76,  77,  78,  79,  80],
            [ 81,  82,  83,  84,  85],
            [ 86,  87,  88,  89,  90],
            [ 91,  92,  93,  94,  95],
            [ 96,  97,  98,  99, 100]]]]]),
 torch.Size([1, 2, 2, 5, 5]))

In [41]:
x[0][1][0][3]

tensor([66, 67, 68, 69, 70])

In [48]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]


tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]],

         [[26, 27, 28, 29, 30],
          [31, 32, 33, 34, 35],
          [36, 37, 38, 39, 40],
          [41, 42, 43, 44, 45],
          [46, 47, 48, 49, 50]]]])

In [47]:
# Get all values of 0th & 1st dimensions but only index 0 of 2nd dimension
x[:, :, 0]

tensor([[[[ 1,  2,  3,  4,  5],
          [ 6,  7,  8,  9, 10],
          [11, 12, 13, 14, 15],
          [16, 17, 18, 19, 20],
          [21, 22, 23, 24, 25]],

         [[51, 52, 53, 54, 55],
          [56, 57, 58, 59, 60],
          [61, 62, 63, 64, 65],
          [66, 67, 68, 69, 70],
          [71, 72, 73, 74, 75]]]])

In [49]:
# Get all values of 0th, 1st and 2nd dimensions but only index 0 of 3rd dimension
x[:, :, :, 0]

tensor([[[[ 1,  2,  3,  4,  5],
          [26, 27, 28, 29, 30]],

         [[51, 52, 53, 54, 55],
          [76, 77, 78, 79, 80]]]])

In [54]:
# Get all values of 0th, 1st , 2nd ,3rd dimensions but only index 0 of 4th dimension
x[:, :, :, :, 0] #This creates a 1-dimensional tensor (also known as a vector).It represents a sequence of one numerical value.

#it it similar to the following except shape
x[0][0][0][0][0] #his creates a 0-dimensional tensor (also known as a scalar). It represents a single numerical value.
x[:, :, :, :, 0].shape, x[0][0][0][0][0].shape

(torch.Size([1, 2, 2, 5]), torch.Size([]))

In [57]:
#tutorial task diff solution
x2 = torch.arange(1, 10).reshape(1, 3, 3)
x2[0,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and numpy

In [63]:
# Numpy Array to tensors
import torch
import numpy as np

array = np.arange(1.0,8.0)
#tensor = torch.arange(1.0,8.0)
tensor = torch.from_numpy(array).type(torch.float32)

array,tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [61]:
array.dtype #default for numpy

dtype('float64')

In [64]:
#TEnsor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability

In [67]:
  rnad_tensor_1=torch.rand(3,4)
  rnad_tensor_2=torch.rand(3,4)
  print(rnad_tensor_1)
  print(rnad_tensor_2)
  rnad_tensor_1 == rnad_tensor_2

tensor([[0.8938, 0.1204, 0.4987, 0.5032],
        [0.9406, 0.2601, 0.3234, 0.4945],
        [0.5560, 0.9736, 0.1874, 0.3802]])
tensor([[0.4575, 0.8156, 0.9433, 0.3682],
        [0.4274, 0.3854, 0.3409, 0.5792],
        [0.5717, 0.2564, 0.9607, 0.1108]])


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [71]:
#random but reproducible tensor
rand_seed = 42
torch.manual_seed(rand_seed)

rnad_tensor_3=torch.rand(3,4)
torch.manual_seed(rand_seed) #have to use it every time
rnad_tensor_4=torch.rand(3,4)
print(rnad_tensor_4)
print(rnad_tensor_3)
rnad_tensor_3 == rnad_tensor_4

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPUs (and making faster computations)

In [1]:
! nvidia-smi

Mon Apr 28 12:32:05 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   35C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### Getting PyTorch to run on the GPU

In [2]:
#check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
#count the number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU

In [5]:
# create a tensor(default is on CPU)
tensor = torch.tensor([1,2,3])
# Tensor not on GPU
print(tensor.device)

cpu


In [9]:
# move tensor to the gpu
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu.device)

cuda:0


### Moving tensors back to the CPU

In [10]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [11]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [14]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')